{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 56,
   "id": "bde198bf-220d-48bd-83ae-41b112bfec39",
   "metadata": {},
   "outputs": [],
   "source": [
    "################################\n",
    "# General Imports\n",
    "################################\n",
    "import csv, math, io, os, os.path, sys, random, time, json, gc, glob\n",
    "from datetime import datetime\n",
    "import joblib\n",
    "from joblib import Parallel, delayed, dump, load\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import seaborn as sb\n",
    "\n",
    "################################\n",
    "# Multiprocessing maybe?\n",
    "################################\n",
    "import multiprocessing\n",
    "multiprocessing\n",
    "\n",
    "################################\n",
    "# Scientific Imports\n",
    "################################\n",
    "import scipy\n",
    "from scipy.signal import butter,filtfilt\n",
    "\n",
    "################################\n",
    "# SKLearn Imports\n",
    "################################\n",
    "#from sklearn.naive_bayes import GaussianNB\n",
    "#from sklearn.naive_bayes import MultinomialNB\n",
    "from sklearn.naive_bayes import CategoricalNB\n",
    "from sklearn.naive_bayes import ComplementNB\n",
    "\n",
    "from sklearn.naive_bayes import BernoulliNB     # <------ USE THIS ONE!!! Bernoulli is good for yes/no classification\n",
    "                                                # https://towardsdatascience.com/naive-bayes-classifier-81d512f50a7c\n",
    "                                    # https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.BernoulliNB.html#sklearn.naive_bayes.BernoulliNB\n",
    "\n",
    "from sklearn import preprocessing\n",
    "from sklearn.metrics import confusion_matrix\n",
    "from sklearn.metrics import accuracy_score\n",
    "from sklearn.metrics import precision_score\n",
    "from sklearn.metrics import recall_score\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.pipeline import make_pipeline\n",
    "from sklearn.preprocessing import FunctionTransformer\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "from sklearn.preprocessing import RobustScaler\n",
    "from sklearn.preprocessing import MaxAbsScaler\n",
    "\n",
    "################################\n",
    "# SKTime Imports\n",
    "################################\n",
    "#from sktime.datatypes._panel._convert import from_2d_array_to_nested, from_nested_to_2d_array, is_nested_dataframe\n",
    "from sktime.forecasting.compose import TransformedTargetForecaster\n",
    "from sktime.forecasting.model_selection import ForecastingGridSearchCV\n",
    "\n",
    "################################\n",
    "# Suppress Warnings\n",
    "################################\n",
    "import warnings\n",
    "warnings.simplefilter(action='ignore', category=UserWarning)\n",
    "warnings.simplefilter(action=\"ignore\", category=RuntimeWarning)\n",
    "warnings.simplefilter(action='ignore', category=FutureWarning)\n",
    "warnings.filterwarnings(\"ignore\", category=np.VisibleDeprecationWarning) \n",
    "\n",
    "################################\n",
    "# Initialisers\n",
    "################################\n",
    "default_rc_params = (16,4)\n",
    "plt.rcParams[\"figure.figsize\"] = default_rc_params\n",
    "sb.set()\n",
    "\n",
    "xNaNs = np.load(\"X_NAN_LIST.npy\")\n",
    "xTime = np.load(\"X_TIME_LIST.npy\")\n",
    "\n",
    "############################################################################################################################################################\n",
    "\n",
    "masterX = np.load(\"True_NOO_fluxes.npy\")\n",
    "masterY = np.load(\"True_NOO_isplanetlist.npy\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "e8794888-edbc-483a-ac69-cc591579cbe6",
   "metadata": {},
   "outputs": [],
   "source": [
    "################################\n",
    "# Functions\n",
    "################################\n",
    "\n",
    "def GetNumDays(time=xTime):\n",
    "    \n",
    "    #xTime = np.load(\"X_TIME_LIST.npy\")\n",
    "    nDays = time[-1]-time[0]\n",
    "    \n",
    "    return (nDays)\n",
    "\n",
    "################################\n",
    "\n",
    "def Every_Nth_Value_EACH(y,nth=40):\n",
    "    return (y[::nth])\n",
    "\n",
    "################################\n",
    "\n",
    "def Every_Nth_Value(masterX,nth=40):\n",
    "    \n",
    "    #print(\"Step 4: Subsample (every nth val)\")\n",
    "    \n",
    "    print(f\"nth = {nth}\")\n",
    "    \n",
    "    biglen = len(masterX)\n",
    "    oldlen = len(masterX[0])\n",
    "    newlen = len(masterX[0][::nth])\n",
    "    print(f\"Old = {oldlen}; new = {newlen}\")\n",
    "    \n",
    "    tmp = np.zeros((biglen,newlen))\n",
    "    \n",
    "    for n,X in enumerate(masterX):\n",
    "        tmp[n] = Every_Nth_Value_EACH(X,nth)\n",
    "        \n",
    "    print(f\"len(tmp) = {len(tmp)}; len(tmp[0]) = {len(tmp[0])}; shape = {np.shape(tmp)}\")\n",
    "    \n",
    "    masterX = np.asarray(tmp)\n",
    "    \n",
    "    return masterX\n",
    "\n",
    "################################\n",
    "\n",
    "def FilterMyData(x,cutoff=0.00005,order=2,xNaNs=xNaNs):\n",
    "    \n",
    "    \"\"\"\n",
    "    Function to apply a Butter Filter to timeseries.\n",
    "    Vars:\n",
    "    \n",
    "    y:        The timeseries. Must be list or np array.\n",
    "    cutoff:   The cutoff frequency. Used to determine where the filter cut off is.\n",
    "    order:    Approximation via polynomial of the order'th degree (2=quadratic, 3=cubic, 4=quartic, etc)\n",
    "    \"\"\"\n",
    "    \n",
    "    # First, let's calculate the observational time period;\n",
    "    # This is done separately so that I can change this in the future for any TESS fits file\n",
    "    numdays       = GetNumDays()\n",
    "    \n",
    "    # Next, fix data                           \n",
    "    xMedian       = np.median(x)                                                    # Get the median value of 'x' before changing it\n",
    "    x             = [xMedian if n in xNaNs else item for n,item in enumerate(x)]    # Change all the missing values to the median value of the whole array\n",
    "    \n",
    "    # Frequency Data Stuff\n",
    "    sec           = numdays*24*60*60   # Number of seconds in the overall observation period\n",
    "    freq          = len(x)/sec         # Frequency, in Hz, ie number of observations per second\n",
    "    # FREQ IS APPROX 1/120 OR ~0.008333333\n",
    "    \n",
    "    # Butter Lowpass Filter\n",
    "    #polynomOrder  = order\n",
    "    nyq           = 0.5 * freq\n",
    "    normal_cutoff = cutoff / nyq\n",
    "    #b, a          = butter(polynomOrder, normal_cutoff, btype='low', analog=False)\n",
    "    b, a          = butter(order, normal_cutoff, btype='low', analog=False)\n",
    "    newX          = filtfilt(b, a, x)\n",
    "    \n",
    "    # Finally, return the new X and Y values\n",
    "    return (newX)\n",
    "\n",
    "################################\n",
    "\n",
    "def FilterAllMyData(masterX,cutoff=0.00005,order=2,nanList=xNaNs):\n",
    "    \n",
    "    #print(\"Step 3: Filter\")\n",
    "    \n",
    "    # Input:  masterX\n",
    "    # Output: masterX with each LC filtered\n",
    "    \n",
    "    for X in masterX:\n",
    "        X[:] = FilterMyData(X,cutoff,order,xNaNs)\n",
    "    \n",
    "    return masterX\n",
    "    \n",
    "################################\n",
    "\n",
    "def Normal(masterX):\n",
    "    \n",
    "    #print(\"Step 2: Normalise\")\n",
    "    \n",
    "    # Takes in 'masterX', my 9154 long array of LCs.\n",
    "    # Need to return a 9154 array, where the daya has been normalised for EACH LC\n",
    "    for X in masterX:\n",
    "        median = np.median(X)\n",
    "        X[:] = np.asarray([(number/median) for number in X])\n",
    "    \n",
    "    return masterX\n",
    "\n",
    "################################\n",
    "\n",
    "def FIXNAN(masterX, nanList=xNaNs):\n",
    "    \n",
    "    #print(\"Step 1: Fix NaN\")\n",
    "    \n",
    "    # Takes in 'masterX', my 9154 long array of LCs.\n",
    "    # Need to return a 9154 array, where the daya has been normalised for EACH LC\n",
    "    for X in masterX:\n",
    "        #print(f\"\\t> Length of X is {len(X)}\")\n",
    "        XMedian = np.median(X)\n",
    "        X[:]= np.asarray([XMedian if n in nanList else item for n,item in enumerate(X)])\n",
    "    \n",
    "    return masterX\n",
    "\n",
    "################################################################\n",
    "\n",
    "def TEST2(masterX,nth=10):\n",
    "    \n",
    "    #print(\"Step 4: Subsample (every nth val)\")\n",
    "    \n",
    "    biglen = len(masterX)\n",
    "    oldlen = len(masterX[0])\n",
    "    newlen = len(masterX[0][::nth])\n",
    "    print(f\"Old = {oldlen}; new = {newlen}\")\n",
    "    \n",
    "    for i in range(len(masterX)):\n",
    "        newX = Every_Nth_Value_EACH(masterX[i],nth)\n",
    "        #print(f\"Length of newX is {len(newX)}\")\n",
    "        masterX[i] = masterX[i][::nth]\n",
    "        masterX[i] = np.resize(masterX[i],len(newX))\n",
    "        #print(f\"Length of NEW masterX[i] is {len(masterX[i])}\")\n",
    "        masterX[i] = newX\n",
    "        \n",
    "    print(f\"len(tmp) = {len(tmp)}; len(tmp[0]) = {len(tmp[0])}; shape = {np.shape(tmp)}\")\n",
    "    \n",
    "    return masterX\n",
    "\n",
    "################################\n",
    "\n",
    "def LCScaler(masterX):\n",
    "    # Gen idlist\n",
    "    idlist=[]\n",
    "    for idx,LC in enumerate(masterX):\n",
    "        if min(LC) < 0:\n",
    "            idlist.append(idx)\n",
    "    \n",
    "    for lc in idlist:\n",
    "        #lc is now an iterator\n",
    "        #for lc in [5785, 5994, 6117, 7769]\n",
    "        \n",
    "        LC = masterX[lc]\n",
    "        \n",
    "        #Min = min()\n",
    "        tmp = np.array([(x - min(LC)) / (max(LC) - min(LC)) for x in LC])\n",
    "        masterX[lc] = tmp\n",
    "    return masterX    \n",
    "\n",
    "################################"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "badc61c1-2d8f-4ab1-bfdc-6baf5404b7c8",
   "metadata": {},
   "source": [
    "## Make the Transformers and the pipeline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "93b70c7e-a57c-449d-975c-1ab5fafa9182",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\t> Model: Complement Naive-Bayes\n",
      "> GENERATING TRANSFORMERS\n",
      "> MAKE PIPELINE\n"
     ]
    }
   ],
   "source": [
    "#algorithm = BernoulliNB()\n",
    "algorithm = ComplementNB()\n",
    "\n",
    "print(\"\\t> Model: Complement Naive-Bayes\")\n",
    "\n",
    "# Make the transformers\n",
    "print(\"> GENERATING TRANSFORMERS\")\n",
    "fnan = FunctionTransformer(FIXNAN)\n",
    "norm = FunctionTransformer(Normal)\n",
    "filt = FunctionTransformer(FilterAllMyData)\n",
    "enth = FunctionTransformer(Every_Nth_Value)\n",
    "lcsc = FunctionTransformer(LCScaler)\n",
    "\n",
    "# Construct the Pipeline\n",
    "print(\"> MAKE PIPELINE\")\n",
    "#pipe = Pipeline(steps=[['fixnan',fnan],['normalise',norm],['filter',filt]]) #,['everynth',enth]])\n",
    "pipe = Pipeline(steps=[['fixnan',fnan],['normalise',norm], ['scale', lcsc],['filter',filt]]) #,['everynth',enth]])\n",
    "#pipe2 = Pipeline(steps=[['filter',filt],['nb', algorithm]])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "985c6abb-0aad-4d4c-834c-92c1d3da0c7b",
   "metadata": {},
   "source": [
    "## Use pipe to transform the data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "485622a2-7cda-46d1-8bf1-52431553ce1b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "> INITIAL TRANSFORMATION\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "array([[0.99940985, 0.99944544, 0.99948084, ..., 1.0000775 , 1.0000783 ,\n",
       "        1.0000789 ],\n",
       "       [1.0212766 , 1.0212839 , 1.0212952 , ..., 0.9403424 , 0.9403301 ,\n",
       "        0.94031984],\n",
       "       [0.97599834, 0.9764575 , 0.97691923, ..., 0.9931079 , 0.9931133 ,\n",
       "        0.99311805],\n",
       "       ...,\n",
       "       [0.9930401 , 0.99337405, 0.99370676, ..., 1.0034362 , 1.0034384 ,\n",
       "        1.0034401 ],\n",
       "       [1.2709858 , 1.2662818 , 1.2615675 , ..., 0.9601087 , 0.96007675,\n",
       "        0.96004766],\n",
       "       [0.9999215 , 0.9999676 , 1.0000149 , ..., 1.0014694 , 1.0014718 ,\n",
       "        1.0014735 ]], dtype=float32)"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "print(\"> INITIAL TRANSFORMATION\")\n",
    "pipe.transform(masterX)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5c804a48-7360-47bc-b169-67fc70ab82f2",
   "metadata": {},
   "source": [
    "## Subsample"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a6a102f5-c527-491d-816d-a342a08c3c1f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "> Subsample\n",
      "nth = 40\n",
      "Old = 20338; new = 509\n",
      "len(tmp) = 8063; len(tmp[0]) = 509; shape = (8063, 509)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "(8063, 20338, 509)"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "print(\"> Subsample\")\n",
    "tmpX = enth.transform(masterX)\n",
    "len(tmpX), len(masterX[0]), len(tmpX[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "d7aaa348-90b5-4f4a-8530-bedf780c33f3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# The above was to check if it worked; IT DOES. So on actual code, replace \"tmpX = ...\" with \"masterX = ...\"\n",
    "masterX = tmpX"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "09aafe8f-fa4f-481c-bd7a-9135c6f32099",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "# Get x values of the sine wave\n",
    "\n",
    "time        = np.arange(0, 10, 0.1);\n",
    "\n",
    "# Amplitude of the sine wave is sine of a variable like time\n",
    "\n",
    "amplitude   = (np.sin(time) + 0.5)\n",
    "\n",
    "# Plot a sine wave using time and amplitude obtained for the sine wave\n",
    "\n",
    "plt.plot(time, amplitude)\n",
    "plt.axhline(y = 0, color = 'r', linestyle = '-')\n",
    "plt.axhline(y = 0.5, color = 'g', linestyle = ':')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c9593483-a558-43b3-adcc-9d951521a849",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "mean = np.mean(amplitude)\n",
    "mx = max(amplitude)\n",
    "mn = min(amplitude)\n",
    "\n",
    "mean, mx, mn"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "465034d1-4d3c-4e5c-a1c3-c5d3a6c0211e",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "ScaledCurve = np.array([(x - mn) / (mx - mn) for x in amplitude])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "786a5b57-c5b8-4713-98c1-b5977212bf20",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "plt.plot(time, newAmp)\n",
    "plt.axhline(y = 0, color = 'r', linestyle = '-')\n",
    "plt.axhline(y = 0.5, color = 'g', linestyle = ':')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1429bdc1-07a0-444d-96ed-644d2929ae74",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "lst = []\n",
    "for idx,LC in enumerate(masterX):\n",
    "    if min(LC) < 0:\n",
    "        lst.append((idx, min(LC)))\n",
    "lst, [i[0] for i in lst]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f789bb7f-a004-442b-9a42-14a4a0ffe4ef",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "def LCScaler(masterX):\n",
    "    # Gen idlist\n",
    "    idlist=[]\n",
    "    for idx,LC in enumerate(masterX):\n",
    "        if min(LC) < 0:\n",
    "            idlst.append(idx)\n",
    "    \n",
    "    for lc in idlist:\n",
    "        #lc is now an iterator\n",
    "        #for lc in [5785, 5994, 6117, 7769]\n",
    "        \n",
    "        LC = masterX[lc]\n",
    "        \n",
    "        #Min = min()\n",
    "        tmp = np.array([(x - min(LC)) / (max(LC) - min(LC)) for x in LC])\n",
    "        masterX[lc] = tmp\n",
    "    return masterX    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2c9af1de-ab53-42e1-9566-e7997c50fe5d",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "idlist = [int(i[0]) for i in lst]\n",
    "print(idlist)\n",
    "\n",
    "masterX = LCScaler(masterX)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f5291344-95e9-46a5-bd7c-8d360ab18b1e",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "plt.plot(masterX[idlist[0]])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "63307dfa-d455-4ae0-a9d0-3eaba9ae1452",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "plot(masterX[idlist[0]])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "72e48ab1-1cd8-4754-bb08-38318b16d2ec",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "nrm2 = FunctionTransformer(LCScaler)\n",
    "nrm2.transform()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5469c2a3-0b41-4a8c-be8a-6b0b1e4fd70a",
   "metadata": {},
   "source": [
    "## Make param grid\n",
    "Note, do not need <code>acronym__params</code> because there will be only one estimator later on"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "516d919b-405d-4282-83ff-f6cb9a8fa56b",
   "metadata": {},
   "outputs": [],
   "source": [
    "#param_grid = {'alpha': [0.2, 0.4, 0.6, 0.8, 1.0]}\n",
    "param_grid = {'alpha': np.linspace(0,1,101,True), #[0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1],\n",
    "                  'fit_prior': [True, False]}"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "06851260-fc04-491e-86ed-c0ef9fa424dd",
   "metadata": {},
   "source": [
    "## Split the (now transformed) data, and make a <code>GridSearchCV</code> with the ALGORITHM ONLY"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "0aa67348-d37d-4e87-b913-3e5df742a142",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "> TEST-TRAIN-SPLIT\n",
      "> GRIDSEARCH\n",
      "> FIT\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "GridSearchCV(estimator=ComplementNB(), n_jobs=3,\n",
       "             param_grid={'alpha': array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,\n",
       "       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,\n",
       "       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,\n",
       "       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,\n",
       "       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,\n",
       "       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,\n",
       "       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,\n",
       "       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,\n",
       "       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,\n",
       "       0.99, 1.  ]),\n",
       "                         'fit_prior': [True, False]},\n",
       "             return_train_score=True)"
      ]
     },
     "execution_count": 33,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Perform data manipulation\n",
    "print(\"> TEST-TRAIN-SPLIT\")\n",
    "X_train, X_test, y_train, y_test = train_test_split(masterX, masterY, random_state=42)\n",
    "\n",
    "# Do gridsearch for svc params\n",
    "print(\"> GRIDSEARCH\")\n",
    "grid = GridSearchCV(algorithm, param_grid, return_train_score=True, n_jobs=3) # 4 programs running at once, 3 jobs = 12 CPUs, 3 for current, 1 spare - 16 total\n",
    "\n",
    "# Fit model\n",
    "print(\"> FIT\")\n",
    "grid.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "25368710-9dd2-4ec8-9681-31850948bee4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "> PREDICT\n"
     ]
    }
   ],
   "source": [
    "# Use svc params and predict\n",
    "print(\"> PREDICT\")\n",
    "model = grid.best_estimator_\n",
    "y_pred = model.predict(X_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "490d6e3c-1ca0-4882-8aba-b798a2aa1188",
   "metadata": {},
   "outputs": [],
   "source": [
    "mAcc = accuracy_score(y_test, y_pred)\n",
    "mPre = precision_score(y_test, y_pred)\n",
    "mRec = recall_score(y_test, y_pred)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "4ab77dc3-db19-4bf8-87d7-7becde9c8754",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(0.5426587301587301, 0.09450830140485313, 0.2578397212543554)"
      ]
     },
     "execution_count": 36,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "mAcc, mPre, mRec"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "4f883725-19d0-450f-a8c6-d816c76f0c79",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "ComplementNB(alpha=0.0)"
      ]
     },
     "execution_count": 37,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "c26a365e-bb2a-4ac7-ae24-5881bb0a04a3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])"
      ]
     },
     "execution_count": 40,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.linspace(0,1,11,True)[1:]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "3a4fe648-c148-4aed-8f91-92d3f4a85872",
   "metadata": {},
   "outputs": [],
   "source": [
    "masterX = np.load(\"True_NOO_fluxes.npy\")[::4]\n",
    "masterY = np.load(\"True_NOO_isplanetlist.npy\")[::4]\n",
    "X_train, X_test, y_train, y_test = train_test_split(masterX, masterY, random_state=42)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "0e1678ad-7d3c-447c-90ee-6bd2ff420cc7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(array([0, 0, 0, ..., 0, 0, 0]), 210, 1512)"
      ]
     },
     "execution_count": 48,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y_train, sum(y_train), len(y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "id": "14fafea3-bab8-4ad4-a7fe-0c1ee47890f1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,\n",
       "        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,\n",
       "        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,\n",
       "        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,\n",
       "        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,\n",
       "        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,\n",
       "        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\n",
       "        0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,\n",
       "        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,\n",
       "        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,\n",
       "        1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,\n",
       "        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,\n",
       "        1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,\n",
       "        0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,\n",
       "        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,\n",
       "        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,\n",
       "        0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,\n",
       "        1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\n",
       "        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\n",
       "        0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\n",
       "        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,\n",
       "        0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,\n",
       "        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),\n",
       " 69,\n",
       " 504)"
      ]
     },
     "execution_count": 49,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y_test, sum(y_test), len(y_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "id": "9faea4d5-99f0-4bd7-b4cc-c760ccc024ad",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "1"
      ]
     },
     "execution_count": 52,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y_test[17]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "id": "85cd222a-82a2-49e1-9cff-891b87862765",
   "metadata": {},
   "outputs": [],
   "source": [
    "def ListCheck(arr):\n",
    "    for n,item in enumerate(arr):\n",
    "        if item == 0 or item == 1:\n",
    "            continue\n",
    "        else:\n",
    "            print (f\"Index {n} has odd value: {item}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "id": "fb61a790-101e-43c9-b3c9-6b24d35987bb",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(None, None)"
      ]
     },
     "execution_count": 55,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ListCheck(y_test), ListCheck(y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 76,
   "id": "9919bed7-b0ee-423f-bd2a-491fae0b2cf5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([1.0e-09, 1.1e-09, 1.2e-09, 1.3e-09, 1.4e-09, 1.5e-09, 1.6e-09,\n",
       "       1.7e-09, 1.8e-09, 1.9e-09, 2.0e-09, 2.1e-09, 2.2e-09, 2.3e-09,\n",
       "       2.4e-09, 2.5e-09, 2.6e-09, 2.7e-09, 2.8e-09, 2.9e-09, 3.0e-09,\n",
       "       3.1e-09, 3.2e-09, 3.3e-09, 3.4e-09, 3.5e-09, 3.6e-09, 3.7e-09,\n",
       "       3.8e-09, 3.9e-09, 4.0e-09, 4.1e-09, 4.2e-09, 4.3e-09, 4.4e-09,\n",
       "       4.5e-09, 4.6e-09, 4.7e-09, 4.8e-09, 4.9e-09, 5.0e-09, 5.1e-09,\n",
       "       5.2e-09, 5.3e-09, 5.4e-09, 5.5e-09, 5.6e-09, 5.7e-09, 5.8e-09,\n",
       "       5.9e-09, 6.0e-09, 6.1e-09, 6.2e-09, 6.3e-09, 6.4e-09, 6.5e-09,\n",
       "       6.6e-09, 6.7e-09, 6.8e-09, 6.9e-09, 7.0e-09, 7.1e-09, 7.2e-09,\n",
       "       7.3e-09, 7.4e-09, 7.5e-09, 7.6e-09, 7.7e-09, 7.8e-09, 7.9e-09,\n",
       "       8.0e-09, 8.1e-09, 8.2e-09, 8.3e-09, 8.4e-09, 8.5e-09, 8.6e-09,\n",
       "       8.7e-09, 8.8e-09, 8.9e-09, 9.0e-09, 9.1e-09, 9.2e-09, 9.3e-09,\n",
       "       9.4e-09, 9.5e-09, 9.6e-09, 9.7e-09, 9.8e-09, 9.9e-09, 1.0e-08])"
      ]
     },
     "execution_count": 76,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.linspace(1e-09,1e-08,91,True)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bb3c1fe4-82da-4612-a91a-f507afe1e291",
   "metadata": {},
   "source": [
    "### Stuff below is testing various NB variations; Gauss/Bern/Categ all come out *exactly the same* so no need doing each"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 123,
   "id": "af47eef0-f822-4201-8dcd-a687828ec97b",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "y_test2 = np.array([\"True\" if x==1 else \"False\" for x in y_test])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 121,
   "id": "5f85634e-a5f9-442f-a3ae-0e483862c4ef",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "newY = masterY\n",
    "\n",
    "newX = np.load(\"NOO_TRANSFORMED_DATA.npy\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 105,
   "id": "18dedc00-6fcb-4d29-a5f5-d6514e8d1d18",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true,
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n",
      "/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 762, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 646, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 83, in predict\n",
      "    jll = self._joint_log_likelihood(X)\n",
      "  File \"/home/jdowzell/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 1461, in _joint_log_likelihood\n",
      "    jll += self.feature_log_prob_[i][:, indices].T\n",
      "IndexError: index 2 is out of bounds for axis 1 with size 2\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "ename": "IndexError",
     "evalue": "index 4 is out of bounds for axis 1 with size 2",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_87185/686693394.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     11\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     12\u001b[0m \u001b[0mmodel\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mgrid\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbest_estimator_\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 13\u001b[0;31m \u001b[0my_pred\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpredict\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX_test\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\u001b[0m in \u001b[0;36mpredict\u001b[0;34m(self, X)\u001b[0m\n\u001b[1;32m     81\u001b[0m         \u001b[0mcheck_is_fitted\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     82\u001b[0m         \u001b[0mX\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_check_X\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 83\u001b[0;31m         \u001b[0mjll\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_joint_log_likelihood\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     84\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mclasses_\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mnp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0margmax\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mjll\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0maxis\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     85\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/sklearn/naive_bayes.py\u001b[0m in \u001b[0;36m_joint_log_likelihood\u001b[0;34m(self, X)\u001b[0m\n\u001b[1;32m   1459\u001b[0m         \u001b[0;32mfor\u001b[0m \u001b[0mi\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mrange\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mn_features_in_\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1460\u001b[0m             \u001b[0mindices\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mX\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mi\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1461\u001b[0;31m             \u001b[0mjll\u001b[0m \u001b[0;34m+=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfeature_log_prob_\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mi\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mindices\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mT\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1462\u001b[0m         \u001b[0mtotal_ll\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mjll\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mclass_log_prior_\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1463\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mtotal_ll\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mIndexError\u001b[0m: index 4 is out of bounds for axis 1 with size 2"
     ]
    }
   ],
   "source": [
    "from sklearn.naive_bayes import GaussianNB\n",
    "algorithm = algorithm = CategoricalNB()\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(newX, newY, random_state=42)\n",
    "\n",
    "params = {'alpha': np.linspace(0,1,101,True)}\n",
    "\n",
    "grid = GridSearchCV(algorithm, params, return_train_score=True, n_jobs=3)\n",
    "\n",
    "grid.fit(X_train, y_train)\n",
    "\n",
    "model = grid.best_estimator_\n",
    "y_pred = model.predict(X_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 110,
   "id": "78677689-a9cb-4566-8c1e-b6dcb7df8e8b",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "newY_test = np.array(['True' if x==1 else 'False' for x in y_test])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 118,
   "id": "472f6fc5-8b74-4710-852e-d8a77cc79658",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "newY_pred = np.array([1 if x==\"True\" else 0 for x in y_pred])\n",
    "newY_test = np.array([1 if x==\"True\" else 0 for x in newY_test])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 122,
   "id": "af29a231-4634-451a-bee9-bd8a53e8cb41",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true,
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(0.21478174603174602, 0.14972972972972973, 0.9651567944250871)"
      ]
     },
     "execution_count": 122,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "mAcc = accuracy_score(newY_test, newY_pred)\n",
    "mPre = precision_score(newY_test, newY_pred)\n",
    "mRec = recall_score(newY_test, newY_pred)\n",
    "\n",
    "mAcc,mPre,mRec"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "01ed7b16-21b8-4c18-9b2c-f2acbd5782e7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
